Fix SPM cache

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -55,14 +55,17 @@ jobs:
         runCmd: >
           set -exu # fail fast, print commands before executing, treat unset variables as an error
 
-          echo "Using LLVM_DIR: $LLVM_DIR"
+          LLVM_DIR="$(llvm-config --prefix)/lib/cmake/llvm"
 
-          ls "$LLVM_DIR"
+          [ -f "$LLVM_DIR/LLVMConfig.cmake" ] || 
+          (echo "LLVMConfig.cmake not found in '$LLVM_DIR'. Available files are:"; 
+          ls "$LLVM_DIR"; 
+          exit 1)
 
           cmake -GNinja -S . -B .cmake-build
           -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }}
           -DBUILD_TESTING=YES -DLLVM_DIR="$LLVM_DIR"
-          
+
           cmake --build .cmake-build
 
           ctest --output-on-failure --parallel --test-dir .cmake-build
@@ -99,8 +102,6 @@ jobs:
           - triple_cpu: x86_64
 
           - os: windows-2025
-            unpackage_command: 7z x -t7z
-            llvm_package_suffix: .7z
             triple_suffix: unknown-windows-msvc17
 
           - os: macos-14
@@ -134,7 +135,7 @@ jobs:
       - name: Set up latest CMake and Ninja
         uses: lukka/get-cmake@latest
         with:
-          cmakeVersion: latestrc
+          cmakeVersion: latest
 
 
       - name: Set up swift
@@ -142,7 +143,7 @@ jobs:
         with:
           swift-version: ${{ env.swift-version }}
 
-      - name: Set up the correct version of Visual Studio Toolchain (Windows)
+      - name: Install Swift-compatible Visual Studio Toolchain (Windows)
         uses: compnerd/gha-setup-vsdevenv@main
         with:
           winsdk: "10.0.22621.0" # Workaround for this: https://forums.swift.org/t/swiftpm-plugin-doesnt-work-with-the-latest-visual-studio-version/78183/14
@@ -157,16 +158,17 @@ jobs:
 
           LLVM_DIR="$(llvm-config --prefix)/lib/cmake/llvm"
 
-          echo "Using LLVM_DIR: $LLVM_DIR"
-          
-          ls "$LLVM_DIR"
-          
-          cmake -G '${{ matrix.cmake_generator }}' 
-          -S . 
-          -B .cmake-build 
-          ${{ matrix.cmake_generator != 'Xcode' && format('-DCMAKE_BUILD_TYPE={0}', matrix.cmake_build_type) || '' }} 
-          -DBUILD_TESTING=YES 
-          -DLLVM_DIR="$LLVM_DIR" 
+          [ -f "$LLVM_DIR/LLVMConfig.cmake" ] || 
+          (echo "LLVMConfig.cmake not found in '$LLVM_DIR'. Available files are:"; 
+          ls "$LLVM_DIR"; 
+          exit 1)
+
+          cmake -G '${{ matrix.cmake_generator }}'
+          -S .
+          -B .cmake-build
+          ${{ matrix.cmake_generator != 'Xcode' && format('-DCMAKE_BUILD_TYPE={0}', matrix.cmake_build_type) || '' }}
+          -DBUILD_TESTING=YES
+          -DLLVM_DIR="$LLVM_DIR"
           ${{ runner.os == 'macOS' && '-DCMAKE_Swift_COMPILER=swiftc -DCMAKE_OSX_SYSROOT=$(xcrun --show-sdk-path)' || '' }}
 
         working-directory: Swifty-LLVM
@@ -178,11 +180,10 @@ jobs:
         run: ctest --output-on-failure --parallel --test-dir Swifty-LLVM/.cmake-build ${{ matrix.cmake_generator == 'Xcode' && format('-C {0}', matrix.cmake_build_type) || '' }}
 
       - name: SPM Cache Setup
-        # Workaround for https://github.com/actions/cache/issues/1541
-        uses: actions/cache@v4.2.2
+        uses: actions/cache@v4.2.4
         with:
-          path: hylo/.build
-          key: ${{ matrix.os }}-${{ matrix.spm_configuration }}-spm
+          path: Swifty-LLVM/.build
+          key: ${{ matrix.os }}-${{ matrix.spm_configuration }}-spm-${{ hashFiles('Swifty-LLVM/**/Package.resolved') || 'no-dependencies' }}
           restore-keys: |
             ${{ matrix.os }}-${{ matrix.spm_configuration }}-spm-
 
