simplify yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -53,12 +53,18 @@ jobs:
         HYLO_LLVM_BUILD_TYPE: ${{ matrix.HYLO_LLVM_BUILD_TYPE }}
       with:
         runCmd: >
-          echo "Using LLVM_DIR: $LLVM_DIR" && \
-          ls "$LLVM_DIR" && \
-          cmake -GNinja -S . -B .cmake-build \
-          -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \ 
-          -DBUILD_TESTING=YES -DLLVM_DIR="$LLVM_DIR" && \
-          cmake --build .cmake-build && \
+          set -exu # fail fast, print commands before executing, treat unset variables as an error
+
+          echo "Using LLVM_DIR: $LLVM_DIR"
+
+          ls "$LLVM_DIR"
+
+          cmake -GNinja -S . -B .cmake-build
+          -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }}
+          -DBUILD_TESTING=YES -DLLVM_DIR="$LLVM_DIR"
+          
+          cmake --build .cmake-build
+
           ctest --output-on-failure --parallel --test-dir .cmake-build
         push: never
 
@@ -79,7 +85,7 @@ jobs:
       matrix:
         os: [macos-14, ubuntu-22.04, windows-2025]
         spm_configuration: [debug, release]
-        cmake_generator: [Ninja, Xcode]
+        cmake_generator: [Ninja] # TODO: add back XCode generator after switching to macos-15: https://github.com/hylo-lang/hylo/issues/1730
 
         exclude:
           - os: ubuntu-22.04
@@ -146,14 +152,23 @@ jobs:
       - name: Configure (CMake)
         # We explicitly point to swiftc in the PATH because otherwise CMake picks up the one in XCode.
         shell: bash
-        run: >-
-          LLVM_DIR="$(llvm-config --prefix)/lib/cmake/llvm" && \
-          echo "Using LLVM_DIR: $LLVM_DIR" && \
-          ls "$LLVM_DIR" && \
-          cmake -G '${{ matrix.cmake_generator }}' -S . -B .cmake-build \
-          ${{ matrix.cmake_generator != 'Xcode' && format('-DCMAKE_BUILD_TYPE={0}', matrix.cmake_build_type) || '' }} \
-          -DBUILD_TESTING=YES -DLLVM_DIR="$LLVM_DIR" \
+        run: >
+          set -exu # fail fast, print commands before executing, treat unset variables as an error
+
+          LLVM_DIR="$(llvm-config --prefix)/lib/cmake/llvm"
+
+          echo "Using LLVM_DIR: $LLVM_DIR"
+          
+          ls "$LLVM_DIR"
+          
+          cmake -G '${{ matrix.cmake_generator }}' 
+          -S . 
+          -B .cmake-build 
+          ${{ matrix.cmake_generator != 'Xcode' && format('-DCMAKE_BUILD_TYPE={0}', matrix.cmake_build_type) || '' }} 
+          -DBUILD_TESTING=YES 
+          -DLLVM_DIR="$LLVM_DIR" 
           ${{ runner.os == 'macOS' && '-DCMAKE_Swift_COMPILER=swiftc -DCMAKE_OSX_SYSROOT=$(xcrun --show-sdk-path)' || '' }}
+
         working-directory: Swifty-LLVM
 
       - name: Build (CMake)
